### PR TITLE
Allow header to be missing if expected value is empty

### LINKED ISSUE #92: Validation tests require the X-WOPI-Lock header to be present, but the docs say otherwise
According to the [documentation for `Unlock`](https://wopi.readthedocs.io/projects/wopirest/en/latest/files/Unlock.html), the `X-WOPI-Lock` header can either have an empty value or be omitted if the file was already unlocked:

> In the case where the file is unlocked, the host must set X-WOPI-Lock to the empty string.

However, if the header is omitted, some tests fail (`UnlockUnlockedFile` and `GetLockOnUnlockedFile`) because the header is missing.

The tests should allow the header to be omitted.

Note: the documentation seems to contradict itself a little farther down the page:

> X-WOPI-Lock – A string value identifying the current lock on the file. **This header must always be included when responding to the request with 409 Conflict.** It should not be included when responding to the request with 200 OK.

I think it should say something like _This header must always be included when responding to the request with 409 Conflict, unless the file is unlocked._ The usual HTTP semantics is that a header with no value is equivalent to the absence of that header.

---

Some additional context

I discovered this issue after migrating my application from ASP.NET Core 2.1 to ASP.NET Core 3.1. Since https://github.com/dotnet/aspnetcore/pull/12486, empty headers are omitted from the response, which makes it impossible to return a header with an empty value. The implication is that it's not possible to build a compliant WOPI host using ASP.NET Core 3.1, given the current tests.

(Actually, there's a workaround: use a string with only whitespace instead of an empty string. But it's brittle and might not work in future versions.)

---

BTW, I'm assuming the interactive WOPI validation is based on the code in this repo. If not, it should also be fixed.

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #92

### CODE REVIEW

**Comment by jgoux** [comment]
I have this error on the test `LockMismatchAfterUnlockAndRelockRequest`, on the first `Unlock`. Could it be merged?

**Comment by srikanthnd** [comment]
Has this issue been resolved?  We still see this error while running validator.  The issue am referring to is : Validation tests require the X-WOPI-Lock header to be present, but the docs say otherwise #92 (https://github.com/microsoft/wopi-validator-core/issues/92?ref=josef.codes?ref=josef.codes)

Below are the screen shots where we can see that the exact issue mentioned by @thomaslevesque still persists with the online validator.

image

image

**Comment by thomaslevesque** [comment]
The fix has been merged, but I suspect it has never been deployed... And as far as I can tell, there's no way to know. This repo is barely maintained. This PR was merged 16 months after it was opened, and nobody from the team ever replied to the issue or the PR. The last commit was more than a year ago.

**Comment by srikanthnd** [comment]
I've had similar conversation with one of the coordinators from WOPI team (he is not with WOPI team anymore) (see: https://github.com/microsoft/Office-Online-Test-Tools-and-Documentation/issues/323) where in he gave no gaurantee as well on when the fix is going to be in place.  This seems very fundamental and yet it takes too much time and effort to get fixed from WOPI team

**Pull request merged**
