### PR TITLE
Add support of exit codes

### LINKED ISSUE #32: Support exit code
When integrating this tool into a CI system it would be great if this tool would return different exit codes depending on the state of the test cases which have been executed.

Would that be possible? THX

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #32

### CODE REVIEW

**Comment by MarcinJuraszek** [comment]
Would it be possible to redeclare `Main` method to return` int` and use the return value to return `1`/`0` based on `failure`/`success`, instead of using `ExitCode`?

**Comment by tylerbutler** [comment]
@MarcinJuraszek Is this more what you had in mind?

https://github.com/Microsoft/wopi-validator-core/compare/master...tylerbutler:exit_codes

It might be a bit over-engineered...

**Comment by MarcinJuraszek** [comment]
Yes, that's kind of what I had in mind.

**Comment by tylerbutler** [comment]
@DeepDiver1975 Can you take a look at PR #41 and see if it meets your needs? If so I'll merge it in and reject this PR.

**Comment by tylerbutler** [comment]
I've merged in PR #41, which was an alternative approach to fixing #32, so I am closing this PR.

**Pull request closed without merging**
